### ISSUE TITLE
Cannot handle a list for source field

### ISSUE THREAD

**Issue by Takadonet** [bioconda/bioconda-utils#168]
I am building a recipe where I have multiple sources. After following the instructions below.
https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#source-from-multiple-sources

Getting the following error from lint.

Traceback (most recent call last):
  File "/tmp/miniconda/bin/bioconda-utils", line 11, in <module>
    load_entry_point('bioconda-utils==0.10.0', 'console_scripts', 'bioconda-utils')()
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 503, in main
    argh.dispatch_commands([build, dag, dependent, lint, duplicates])
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/tmp/miniconda/lib/python3.5/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/cli.py", line 409, in build
    mulled_upload_target=mulled_upload_target,
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/build.py", line 267, in build_recipes
    recipes, env_matrix, check_channels, force=force)
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 743, in filter_recipes
    pkg = built_package_path(recipe, env)
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 519, in built_package_path
    path = api.get_output_file_path(meta, config=config)
  File "/tmp/miniconda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 111, in temp_env
    yield
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 517, in built_package_path
    meta = MetaData(recipe, config=config)
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/metadata.py", line 437, in __init__
    self.parse_again(config=config, permit_undefined_jinja=True)
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/metadata.py", line 470, in parse_again
    config=config, path=self.meta_path)
  File "/tmp/miniconda/lib/python3.5/site-packages/conda_build/metadata.py", line 196, in parse
    (field, res[field].__class__.__name__, path))
RuntimeError: The source field should be a dict, not list in file recipes/bcftools-snvphyl-plugin/meta.yaml.
Exception ignored in: <bound method RecipeBuilder.__del__ of <bioconda_utils.docker_utils.RecipeBuilder object at 0x7fc02cba2ef0>>
Traceback (most recent call last):
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 367, in __del__
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/docker_utils.py", line 507, in cleanup
  File "/tmp/miniconda/lib/python3.5/site-packages/bioconda_utils/utils.py", line 194, in run
  File "/tmp/miniconda/lib/python3.5/subprocess.py", line 693, in run
  File "/tmp/miniconda/lib/python3.5/subprocess.py", line 947, in __init__
  File "/tmp/miniconda/lib/python3.5/subprocess.py", line 1481, in _execute_child
  File "/tmp/miniconda/lib/python3.5/os.py", line 673, in get_exec_path
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 887, in _find_spec
TypeError: 'NoneType' object is not iterable

Looks like it does not like getting a list instead of a dictionary. Any ideas how to skip this? Is there a flag I can pass to ./simulate-travis.py or travis itself to ignore linting?

**Comment by daler** [comment]
@Takadonet multiple sources are only supported by conda-build v3, and bioconda does not support v3 yet. You'll have to use a single source for now.

**Comment by daler** [comment]
If you submit a PR with the recipe you're working on, folks here would be happy to help you get it working.
