### ISSUE TITLE
lint should warn about meta.yml files

### ISSUE THREAD

**Issue by rvalieris** [bioconda/bioconda-utils#341]
I saw this before but forgot to report, if the meta file is named `meta.yml` the recipe won't be built. but it will look like the CI passed.

the other option would be to have the build system support both yml and yaml extensions but I suspect thats a little harder, I think "yaml" is hardcoded in multiple places.

example of the problem: https://github.com/bioconda/bioconda-recipes/pull/10475#issuecomment-414315405

**Comment by epruesse** [comment]
Right now, lint and build only check for modifications to meta.yaml, build.sh and blacklist, so the new folder in recipes won't get checked at all.

**Comment by aliciaaevans** [comment]
This continues to happen (https://github.com/bioconda/bioconda-recipes/pull/49072), and it also breaks the nightly builds.

It's mostly an annoyance.

**Comment by aliciaaevans** [comment]
Here's the error that occurs on the nightly build. It might be worth also fixing that so it skips the recipe with an error message rather than exit immediately.
```
00:12:11 BIOCONDA INFO Generating DAG
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/utils.py", line 491, in load_meta_fast
    template = jinja_silent_undef.from_string(open(pth, 'r', encoding='utf-8').read())
FileNotFoundError: [Errno 2] No such file or directory: 'recipes/gtdb_to_taxdump/meta.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/utils.py", line 495, in load_meta_fast
    raise ValueError('Problem inspecting {0}'.format(recipe))
ValueError: Problem inspecting recipes/gtdb_to_taxdump
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/mambaforge/envs/bioconda/bin/bioconda-utils", line 8, in <module>
    sys.exit(main())
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 1124, in main
    argh.dispatch_commands([
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 510, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 198, in dispatch
    return run_endpoint_function(
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 269, in run_endpoint_function
    return _process_command_output(lines, output_file, raw_output, always_flush)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 289, in _process_command_output
    for line in lines:
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 414, in _execute_command
    for line in result:
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/argh/dispatching.py", line 394, in _call
    result = function(*positional_values, **values_by_name)
  File "<boltons.funcutils.FunctionBuilder-5>", line 2, in build
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 137, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-4>", line 2, in build
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 66, in wrapper
    func(*args, **kwargs)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/cli.py", line 498, in build
    success = build_recipes(recipe_folder, config, recipes,
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/build.py", line 386, in build_recipes
    dag, name2recipes = graph.build(recipes, config=config_path, blacklist=blacklist)
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/graph.py", line 52, in build
    metadata = list(utils.parallel_iter(utils.load_meta_fast, recipes, "Loading Recipes"))
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/bioconda_utils/utils.py", line 828, in parallel_iter
    yield from tqdm(
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/site-packages/tqdm/std.py", line 1169, in __iter__
    for obj in iterable:
  File "/opt/mambaforge/envs/bioconda/lib/python3.10/multiprocessing/pool.py", line 873, in next
    raise value
ValueError: Problem inspecting recipes/gtdb_to_taxdump
```
