### ISSUE TITLE
Linter fails in channel_dataframe()

### ISSUE THREAD

**Issue by epruesse** [bioconda/bioconda-utils#360]
E.g. in https://github.com/bioconda/bioconda-recipes/pull/12441, https://circleci.com/gh/bioconda/bioconda-recipes/35848?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
```
#!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml \
--loglevel debug --full-report \
--git-range master HEAD

Traceback (most recent call last):
  File "/home/circleci/project/miniconda/bin/bioconda-utils", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 657, in main
    bioconductor_skeleton, pypi_check, clean_cran_skeleton,
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 228, in lint
    df = linting.channel_dataframe(cache=cache)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/bioconda_utils/linting.py", line 123, in channel_dataframe
    x = pd.DataFrame(repo)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 461, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 6163, in _arrays_to_mgr
    index = extract_index(arrays)
  File "/home/circleci/project/miniconda/lib/python3.6/site-packages/pandas/core/frame.py", line 6214, in extract_index
    raise ValueError('Mixing dicts with non-Series may lead to '
ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.
Exited with code 1
```

**Comment by epruesse** [comment]
ping @bioconda/core Help appreciated. I think this is now permanent.

**Comment by epruesse** [comment]
In case it "works again" soon, here's a pickle of the `repo` object:
[broken_cf_linux.pkl.gz](https://github.com/bioconda/bioconda-utils/files/2635418/broken_cf_linux.pkl.gz)

**Comment by rob-p** [comment]
So, is this problem fundamentally upstream?  Is there anything individual packages can do to address it?

**Comment by epruesse** [comment]
I think we should be resilient. Working on it ...

**Comment by k3yavi** [comment]
I was wondering if there is any update on this? Seems like a bioconda wide outage for PR, is there a way to promote this issue to a higher priority ?

**Comment by pcm32** [comment]
The above PR for https://github.com/bioconda/bioconda-recipes/pull/12347 was merged as tests passed, but then the uploads failed due to the issue mentioned on this PR.

**Comment by dpryan79** [comment]
You should be able to close this now.

**Comment by epruesse** [comment]
Thanks @dpryan79

**Comment by dpryan79** [comment]
@mshakya Try updating bioconda-utils.

**Comment by epruesse** [comment]
@mshakya The entire piece of code was rewritten. Your `circleci build` might be using an old image perhaps?

**Comment by mshakya** [comment]
@epruesse that did the trick. I had the old image. I pulled the new image `docker pull bioconda/bioconda-utils-build-env`. Thank you!
