### ISSUE TITLE
errors when running simulate-travis.py

### ISSUE THREAD

**Issue by sebastian-luna-valero** [bioconda/bioconda-utils#37]
Hello,

I am using `./simulate-travis.py --packages mypackagename --loglevel=debug` and getting the error below.

However, I don't know how to go from there. Do you have an idea?

First error:
```
ERROR bioconda_utils.build:build(112): BIOCONDA BUILD FAILED recipes/cgat-scripts, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(113): COMMAND: docker run --net host --rm -v /tmp/tmpcpkgziem/build_script.bash:/opt/build_script.bash -v /sebastian/conda/conda3-build/bioconda/conda-bld:/opt/host-conda-bld -v /ifs/devel/system/conda/bioconda-recipes/recipes/cgat-scripts:/opt/recipe -e CONDA_PY=27 -e CONDA_GMP=5.1 -e CONDA_BOOST=1.60 -e CONDA_GSL=1.16 -e CONDA_NCURSES=5.9 -e CONDA_PERL=5.22.0 -e CONDA_R=3.3.1 -e CONDA_NPY=110 tmp-bioconda-builder /bin/bash /opt/build_script.bash
ERROR bioconda_utils.build:build(114): STDOUT+STDERR: bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

seems to be explained here:
http://serverfault.com/questions/411307/cannot-set-terminal-process-group-during-su-to-another-user-as-login-shell

Second error:
```
ERROR bioconda_utils.build:build_recipes(355): BIOCONDA BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(366): BIOCONDA BUILD SUMMARY: FAILED recipe cgat-scripts-0.2.6-py27r3.3.1_0.tar.bz2, environment CONDA_PY=27;CONDA_PERL=5.22.0;CONDA_R=3.3.1;CONDA_NPY=110;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_BOOST=1.60;CONDA_NCURSES=5.9
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/sebastian/conda/conda3-build/bioconda/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1
```

does not explain why the build is failing for my recipe. How can I get it to print it?

Please see full error below.

Best regards,
Sebastian

```
./simulate-travis.py --packages cgat-scripts --loglevel=debug
+ bioconda-utils build recipes config.yml --docker --loglevel=info --mulled-test --packages cgat-scripts --loglevel=debug
INFO bioconda_utils.docker_utils:_pull_image(308): BIOCONDA DOCKER: Pulling docker image condaforge/linux-anvil
DEBUG bioconda_utils.docker_utils:_pull_image(310): BIOCONDA DOCKER: stdout+stderr: Using default tag: latest
latest: Pulling from condaforge/linux-anvil
Digest: sha256:a2e1bf0fae91b9f7a0305aa12efd7a0a3e80af2e13a7e8eba8363ff8425148aa
Status: Image is up to date for condaforge/linux-anvil:latest

INFO bioconda_utils.docker_utils:_pull_image(314): BIOCONDA DOCKER: Done pulling image
DEBUG bioconda_utils.docker_utils:_build_image(325): BIOCONDA DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmpbckuak52
DEBUG bioconda_utils.docker_utils:_build_image(338): Dockerfile:

FROM condaforge/linux-anvil
COPY requirements.txt /tmp/requirements.txt
RUN /opt/conda/bin/conda install --file /tmp/requirements.txt

INFO bioconda_utils.docker_utils:_build_image(354): BIOCONDA DOCKER: Built docker image tag=tmp-bioconda-builder
INFO bioconda_utils.build:build_recipes(213): blacklist: bioconductor-bubbletree, bioconductor-cexor, bioconductor-csaw, bioconductor-dada2, bioconductor-deseq2/1.10.1, bioconductor-dexseq, bioconductor-diffbind, bioconductor-ebseq, bioconductor-genelendatabase/1.6.0, bioconductor-iranges/2.4.6, bioconductor-iranges/2.4.7, bioconductor-limma/3.26.7, bioconductor-limma/3.28.2, bioconductor-limma/3.28.6, bioconductor-minfi, bioconductor-mmdiff, bioconductor-qdnaseq, bioconductor-s4vectors/0.8.7, bioconductor-shortread, bioconductor-summarizedexperiment/1.0.2, bioconductor-systempiper, cap-mirseq, lefse, mgkit, mysqlclient, poretools/0.5.0, poretools/0.5.1, r-batchjobs, r-gsalib, r-hdrcde, r-knitr, r-ks, r-mixomics, r-mutoss, r-phonr, r-rainbow, r-readr, r-sartools/1.2.0, r-spp, rsem, triform2, vsearch
DEBUG bioconda_utils.utils:get_recipes(245): get_recipes(recipes, package='['cgat-scripts']'): cgat-scripts
DEBUG bioconda_utils.build:build_recipes(224): recipes/cgat-scripts
DEBUG bioconda_utils.build:build_recipes(229): recipes: ['recipes/cgat-scripts']
INFO bioconda_utils.build:build_recipes(248): Filtering recipes
DEBUG bioconda_utils.utils:filter_recipes(494): recipes: ['recipes/cgat-scripts']

DEBUG bioconda_utils.utils:tobuild(491): BIOCONDA FILTER: building cgat-scripts-0.2.6-py27r3.3.1_0.tar.bz2 because it is not in channels does not define skip, and force is not specified
DEBUG bioconda_utils.utils:tobuild(486): BIOCONDA FILTER: not building cgat-scripts-0.2.6-py34r3.3.1_0.tar.bz2 because it defines skip for this env
DEBUG bioconda_utils.utils:tobuild(486): BIOCONDA FILTER: not building cgat-scripts-0.2.6-py35r3.3.1_0.tar.bz2 because it defines skip for this env

INFO bioconda_utils.build:build_recipes(265): Building and testing 1 recipes in total
INFO bioconda_utils.build:build_recipes(266): Recipes to build: 
cgat-scripts
INFO bioconda_utils.build:build_recipes(303): Building and testing subdag 0 of 1 (1 recipes)
INFO bioconda_utils.build:build(58): BIOCONDA BUILD START recipes/cgat-scripts, env: CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
DEBUG bioconda_utils.build:build(74): build_args: ['--no-build-id', '--no-anaconda-upload']
DEBUG bioconda_utils.build:build(75): channel_args: ['--channel', 'bioconda', '--channel', 'r', '--channel', 'defaults', '--channel', 'conda-forge']
DEBUG bioconda_utils.docker_utils:build_recipe(391): BIOCONDA DOCKER: Container build script: 

#!/bin/bash
set -e

conda install conda-build=2.0.7

# Add the host's mounted conda-bld dir so that we can use its contents as
# dependencies for building this recipe.
#
# Note that if the directory didn't exist on the host, then the staging area
# will exist in the container but will be empty.  Channels expect at least
# a linux-64 directory within that directory, so we make sure it exists before
# adding the channel.
mkdir -p /opt/host-conda-bld/linux-64
conda config --add channels file:///opt/host-conda-bld

# The actual building....
conda build --channel bioconda --channel r --channel defaults --channel conda-forge --no-build-id --no-anaconda-upload /opt/recipe

# Identify the output package
OUTPUT=$(conda build /opt/recipe --output)

# Some args to conda-build make it run and exit 0 without creating a package
# (e.g., -h or --skip-existing), so check to see if there's anything to copy
# over first.
if [[ -e $OUTPUT ]]; then

    # Copy over the recipe from where the container built it to the mounted
    # conda-bld dir from the host. Since docker containers are Linux, we assume
    # here that we want the linux-64 arch.
    cp $OUTPUT /opt/host-conda-bld/linux-64

    # Ensure permissions are correct on the host.
    HOST_USER=1362
    chown $HOST_USER:$HOST_USER /opt/host-conda-bld/linux-64/$(basename $OUTPUT)

    conda index /opt/host-conda-bld/linux-64
fi

DEBUG bioconda_utils.docker_utils:build_recipe(413): BIOCONDA DOCKER: cmd: ['docker', 'run', '--net', 'host', '--rm', '-v', '/tmp/tmpcpkgziem/build_script.bash:/opt/build_script.bash', '-v', '/sebastian/conda/conda3-build/bioconda/conda-bld:/opt/host-conda-bld', '-v', '/ifs/devel/system/conda/bioconda-recipes/recipes/cgat-scripts:/opt/recipe', '-e', 'CONDA_PY=27', '-e', 'CONDA_GMP=5.1', '-e', 'CONDA_BOOST=1.60', '-e', 'CONDA_GSL=1.16', '-e', 'CONDA_NCURSES=5.9', '-e', 'CONDA_PERL=5.22.0', '-e', 'CONDA_R=3.3.1', '-e', 'CONDA_NPY=110', 'tmp-bioconda-builder', '/bin/bash', '/opt/build_script.bash']
ERROR bioconda_utils.build:build(112): BIOCONDA BUILD FAILED recipes/cgat-scripts, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(113): COMMAND: docker run --net host --rm -v /tmp/tmpcpkgziem/build_script.bash:/opt/build_script.bash -v /sebastian/conda/conda3-build/bioconda/conda-bld:/opt/host-conda-bld -v /ifs/devel/system/conda/bioconda-recipes/recipes/cgat-scripts:/opt/recipe -e CONDA_PY=27 -e CONDA_GMP=5.1 -e CONDA_BOOST=1.60 -e CONDA_GSL=1.16 -e CONDA_NCURSES=5.9 -e CONDA_PERL=5.22.0 -e CONDA_R=3.3.1 -e CONDA_NPY=110 tmp-bioconda-builder /bin/bash /opt/build_script.bash
ERROR bioconda_utils.build:build(114): STDOUT+STDERR: bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /opt/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-build-2.0.7          |           py35_0         275 KB  defaults

The following packages will be UPDATED:

    conda:       4.1.11-py35_1 conda-forge --> 4.1.12-py35_0 conda-forge
    conda-build: 2.0.4-py35_0  defaults    --> 2.0.7-py35_0  defaults   

Proceed ([y]/n)? 
Using Anaconda Cloud api site https://api.anaconda.org
Fetching packages ...
conda-build-2. 100% |###############################| Time: 0:00:00  12.78 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Using Anaconda Cloud api site https://api.anaconda.org
BUILD START: cgat-scripts-0.2.6-py27r3.3.1_0
updating index in: /opt/conda/conda-bld/linux-64
updating index in: /opt/conda/conda-bld/noarch
Could not find URL: file:///opt/host-conda-bld/linux-64/

ERROR bioconda_utils.build:build_recipes(355): BIOCONDA BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(366): BIOCONDA BUILD SUMMARY: FAILED recipe cgat-scripts-0.2.6-py27r3.3.1_0.tar.bz2, environment CONDA_PY=27;CONDA_PERL=5.22.0;CONDA_R=3.3.1;CONDA_NPY=110;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_BOOST=1.60;CONDA_NCURSES=5.9
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/sebastian/conda/conda3-build/bioconda/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1
```

**Comment by bgruening** [comment]
> ERROR bioconda_utils.build:build(114): STDOUT+STDERR: bash: cannot set terminal process group (-1): Inappropriate ioctl for device

This error is a artifact of the build-system you can safely ignore it.
The second error looks like you don't have a folder in this location `file:///opt/host-conda-bld/linux-64/`. This was a bug that was recently fixed and I think updating all scripts and packages will fix it.

Hope this helps, feel free to reopen if you still see this error!
Bjoern

**Comment by daler** [comment]
Also see new docs at https://bioconda.github.io/bioconda-utils/, and specifically the troubleshooting section for the first error: https://bioconda.github.io/bioconda-utils/troubleshooting.html

**Comment by sebastian-luna-valero** [comment]
Many thanks for your great work!

I think I am still having the same problem. Here is the new output:
```
+ bioconda-utils build recipes config.yml --docker --loglevel=info --mulled-test --packages cgat-scripts --loglevel=debug
INFO bioconda_utils.docker_utils:_pull_image(308): BIOCONDA DOCKER: Pulling docker image condaforge/linux-anvil
DEBUG bioconda_utils.docker_utils:_pull_image(310): BIOCONDA DOCKER: stdout+stderr: Using default tag: latest
latest: Pulling from condaforge/linux-anvil
Digest: sha256:a2e1bf0fae91b9f7a0305aa12efd7a0a3e80af2e13a7e8eba8363ff8425148aa
Status: Image is up to date for condaforge/linux-anvil:latest

INFO bioconda_utils.docker_utils:_pull_image(314): BIOCONDA DOCKER: Done pulling image
DEBUG bioconda_utils.docker_utils:_build_image(325): BIOCONDA DOCKER: Building image "tmp-bioconda-builder" from /tmp/tmp3bs3ugau
DEBUG bioconda_utils.docker_utils:_build_image(338): Dockerfile:

FROM condaforge/linux-anvil
COPY requirements.txt /tmp/requirements.txt
RUN /opt/conda/bin/conda install --file /tmp/requirements.txt

INFO bioconda_utils.docker_utils:_build_image(354): BIOCONDA DOCKER: Built docker image tag=tmp-bioconda-builder
INFO bioconda_utils.build:build_recipes(213): blacklist: bioconductor-bubbletree, bioconductor-cexor, bioconductor-csaw, bioconductor-dada2, bioconductor-deseq2/1.10.1, bioconductor-dexseq, bioconductor-diffbind, bioconductor-ebseq, bioconductor-genelendatabase/1.6.0, bioconductor-iranges/2.4.6, bioconductor-iranges/2.4.7, bioconductor-limma/3.26.7, bioconductor-limma/3.28.2, bioconductor-limma/3.28.6, bioconductor-minfi, bioconductor-mmdiff, bioconductor-qdnaseq, bioconductor-s4vectors/0.8.7, bioconductor-shortread, bioconductor-summarizedexperiment/1.0.2, bioconductor-systempiper, cap-mirseq, mgkit, mysqlclient, poretools/0.5.0, poretools/0.5.1, r-batchjobs, r-gsalib, r-hdrcde, r-knitr, r-ks, r-mixomics, r-mutoss, r-phonr, r-rainbow, r-readr, r-sartools/1.2.0, r-spp, rsem, triform2, vsearch
DEBUG bioconda_utils.utils:get_recipes(245): get_recipes(recipes, package='['cgat-scripts']'): cgat-scripts
DEBUG bioconda_utils.build:build_recipes(224): recipes/cgat-scripts
DEBUG bioconda_utils.build:build_recipes(229): recipes: ['recipes/cgat-scripts']
INFO bioconda_utils.build:build_recipes(248): Filtering recipes
DEBUG bioconda_utils.utils:filter_recipes(494): recipes: ['recipes/cgat-scripts']

DEBUG bioconda_utils.utils:tobuild(491): BIOCONDA FILTER: building cgat-scripts-0.2.6-py27r3.3.1_0.tar.bz2 because it is not in channels does not define skip, and force is not specified
DEBUG bioconda_utils.utils:tobuild(486): BIOCONDA FILTER: not building cgat-scripts-0.2.6-py34r3.3.1_0.tar.bz2 because it defines skip for this env
DEBUG bioconda_utils.utils:tobuild(486): BIOCONDA FILTER: not building cgat-scripts-0.2.6-py35r3.3.1_0.tar.bz2 because it defines skip for this env
Filtering 1 of 1 (100.0%) recipes/cgat-scripts
INFO bioconda_utils.build:build_recipes(265): Building and testing 1 recipes in total
INFO bioconda_utils.build:build_recipes(266): Recipes to build: 
cgat-scripts
INFO bioconda_utils.build:build_recipes(303): Building and testing subdag 0 of 1 (1 recipes)
INFO bioconda_utils.build:build(58): BIOCONDA BUILD START recipes/cgat-scripts, env: CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
DEBUG bioconda_utils.build:build(74): build_args: ['--no-build-id', '--no-anaconda-upload']
DEBUG bioconda_utils.build:build(75): channel_args: ['--channel', 'bioconda', '--channel', 'r', '--channel', 'defaults', '--channel', 'conda-forge']
DEBUG bioconda_utils.docker_utils:build_recipe(391): BIOCONDA DOCKER: Container build script: 

#!/bin/bash
set -e

conda install conda-build=2.0.7

# Add the host's mounted conda-bld dir so that we can use its contents as
# dependencies for building this recipe.
#
# Note that if the directory didn't exist on the host, then the staging area
# will exist in the container but will be empty.  Channels expect at least
# a linux-64 directory within that directory, so we make sure it exists before
# adding the channel.
mkdir -p /opt/host-conda-bld/linux-64
conda config --add channels file:///opt/host-conda-bld

# The actual building....
conda build --channel bioconda --channel r --channel defaults --channel conda-forge --no-build-id --no-anaconda-upload /opt/recipe

# Identify the output package
OUTPUT=$(conda build /opt/recipe --output)

# Some args to conda-build make it run and exit 0 without creating a package
# (e.g., -h or --skip-existing), so check to see if there's anything to copy
# over first.
if [[ -e $OUTPUT ]]; then

    # Copy over the recipe from where the container built it to the mounted
    # conda-bld dir from the host. Since docker containers are Linux, we assume
    # here that we want the linux-64 arch.
    cp $OUTPUT /opt/host-conda-bld/linux-64

    # Ensure permissions are correct on the host.
    HOST_USER=1362
    chown $HOST_USER:$HOST_USER /opt/host-conda-bld/linux-64/$(basename $OUTPUT)

    conda index /opt/host-conda-bld/linux-64
fi

DEBUG bioconda_utils.docker_utils:build_recipe(413): BIOCONDA DOCKER: cmd: ['docker', 'run', '--net', 'host', '--rm', '-v', '/tmp/tmpdi0bcwmo/build_script.bash:/opt/build_script.bash', '-v', '/sebastian/i35/conda-bld:/opt/host-conda-bld', '-v', '/ifs/devel/system/conda/bioconda-recipes/recipes/cgat-scripts:/opt/recipe', '-e', 'CONDA_PERL=5.22.0', '-e', 'CONDA_GMP=5.1', '-e', 'CONDA_NCURSES=5.9', '-e', 'CONDA_BOOST=1.60', '-e', 'CONDA_GSL=1.16', '-e', 'CONDA_NPY=110', '-e', 'CONDA_PY=27', '-e', 'CONDA_R=3.3.1', 'tmp-bioconda-builder', '/bin/bash', '/opt/build_script.bash']
ERROR bioconda_utils.build:build(112): BIOCONDA BUILD FAILED recipes/cgat-scripts, CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_GSL=1.16;CONDA_NCURSES=5.9;CONDA_NPY=110;CONDA_PERL=5.22.0;CONDA_PY=27;CONDA_R=3.3.1
ERROR bioconda_utils.build:build(113): COMMAND: docker run --net host --rm -v /tmp/tmpdi0bcwmo/build_script.bash:/opt/build_script.bash -v /sebastian/i35/conda-bld:/opt/host-conda-bld -v /ifs/devel/system/conda/bioconda-recipes/recipes/cgat-scripts:/opt/recipe -e CONDA_PERL=5.22.0 -e CONDA_GMP=5.1 -e CONDA_NCURSES=5.9 -e CONDA_BOOST=1.60 -e CONDA_GSL=1.16 -e CONDA_NPY=110 -e CONDA_PY=27 -e CONDA_R=3.3.1 tmp-bioconda-builder /bin/bash /opt/build_script.bash
ERROR bioconda_utils.build:build(114): STDOUT+STDERR: bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /opt/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-build-2.0.7          |           py35_0         275 KB  defaults

The following packages will be UPDATED:

    conda:       4.1.11-py35_1 conda-forge --> 4.1.12-py35_0 conda-forge
    conda-build: 2.0.4-py35_0  defaults    --> 2.0.7-py35_0  defaults   

Proceed ([y]/n)? 
Using Anaconda Cloud api site https://api.anaconda.org
Fetching packages ...
conda-build-2. 100% |###############################| Time: 0:00:00  10.63 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Using Anaconda Cloud api site https://api.anaconda.org
BUILD START: cgat-scripts-0.2.6-py27r3.3.1_0
updating index in: /opt/conda/conda-bld/linux-64
updating index in: /opt/conda/conda-bld/noarch
Could not find URL: file:///opt/host-conda-bld/linux-64/

ERROR bioconda_utils.build:build_recipes(355): BIOCONDA BUILD SUMMARY: of 1 recipes, 1 failed and 0 were skipped. Details of recipes and environments follow.
ERROR bioconda_utils.build:build_recipes(366): BIOCONDA BUILD SUMMARY: FAILED recipe cgat-scripts-0.2.6-py27r3.3.1_0.tar.bz2, environment CONDA_PERL=5.22.0;CONDA_NCURSES=5.9;CONDA_GSL=1.16;CONDA_NPY=110;CONDA_R=3.3.1;CONDA_BOOST=1.60;CONDA_GMP=5.1;CONDA_PY=27
Traceback (most recent call last):
  File "./simulate-travis.py", line 150, in <module>
    sp.run(['scripts/travis-run.sh'], env=env, universal_newlines=True, check=True)
  File "/sebastian/i35/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['scripts/travis-run.sh']' returned non-zero exit status 1
```

Here is the environment:
```
$ conda info
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.7
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : /sebastian/i35  (writable)
    default environment : /sebastian/i35
       envs directories : /sebastian/i35/envs
          package cache : /sebastian/i35/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                          https://conda.anaconda.org/bioconda/noarch/
                          https://conda.anaconda.org/r/linux-64/
                          https://conda.anaconda.org/r/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://conda.anaconda.org/conda-forge/linux-64/
                          https://conda.anaconda.org/conda-forge/noarch/
            config file : /ifs/home/sebastian/.condarc
           offline mode : False

$ conda list
# packages in environment at /sebastian/i35:
#
alabaster                 0.7.9                    py35_0  
anaconda-client           1.5.2                    py35_0  
argh                      0.26.2                   py35_0    bioconda
babel                     2.3.4                    py35_0  
beautifulsoup4            4.4.1                    py35_0  
bioconda-utils            0.9.0                     <pip>
clyent                    1.2.2                    py35_0  
conda                     4.2.9                    py35_0  
conda-build               2.0.7                    py35_0  
conda-env                 2.6.0                         0  
conda-verify              2.0.0                    py35_0  
decorator                 4.0.10                   py35_0  
docutils                  0.12                     py35_2  
filelock                  2.0.7                    py35_0  
galaxy-lib                16.10.9                  py35_0    bioconda
imagesize                 0.7.1                    py35_0  
involucro                 1.1.2                         0    bioconda
jinja2                    2.8                      py35_1  
jsonschema                2.5.1                    py35_0  
markupsafe                0.23                     py35_2  
networkx                  1.11                     py35_0  
openssl                   1.0.2j                        0  
patchelf                  0.9                           0  
pip                       9.0.1                    py35_0  
pkginfo                   1.4.1                    py35_0  
pyaml                     15.8.2                   py35_0    bioconda
pycosat                   0.6.1                    py35_1  
pycrypto                  2.6.1                    py35_4  
pydotplus                 2.0.2                    py35_0    bioconda
pygments                  2.1.3                    py35_0  
pyparsing                 2.1.4                    py35_0  
python                    3.5.2                         0  
python-dateutil           2.3                      py35_0    bioconda
pytz                      2016.7                   py35_0  
pyyaml                    3.12                     py35_0  
readline                  6.2                           2  
requests                  2.10.0                   py35_0  
ruamel_yaml               0.11.14                  py35_0  
setuptools                27.2.0                   py35_0  
six                       1.10.0                   py35_0  
snowballstemmer           1.2.1                    py35_0  
sphinx                    1.4.1                    py35_0  
sphinx_rtd_theme          0.1.9                    py35_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py35_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3  

$ pip list
alabaster (0.7.9)
anaconda-client (1.5.2+0.g2c11c88.dirty)
argh (0.26.2)
Babel (2.3.4)
beautifulsoup4 (4.4.1)
bioconda-utils (0.9.0)
clyent (1.2.2)
conda (4.2.9)
conda-build (2.0.7)
conda-verify (2.0.0)
decorator (4.0.10)
docutils (0.12)
filelock (2.0.7)
galaxy-lib (16.10.9)
imagesize (0.7.1)
Jinja2 (2.8)
jsonschema (2.5.1)
MarkupSafe (0.23)
networkx (1.11)
pip (9.0.1)
pkginfo (1.4.1)
pyaml (15.8.2)
pycosat (0.6.1)
pycrypto (2.6.1)
pydotplus (2.0.2)
Pygments (2.1.3)
pyparsing (2.1.4)
python-dateutil (2.3)
pytz (2016.7)
PyYAML (3.12)
requests (2.10.0)
ruamel-yaml (-VERSION)
setuptools (27.2.0)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.4.1)
sphinx-rtd-theme (0.1.9)
wheel (0.29.0)

$ docker images 
REPOSITORY               TAG                 IMAGE ID            CREATED             SIZE
tmp-bioconda-builder     latest              111afc5cd52d        11 minutes ago      763.4 MB
condaforge/linux-anvil   latest              20e975f71d5c        13 days ago         736.4 MB
```

Many thanks,
Sebastian.

**Comment by daler** [comment]
I've seen this issue reported at least once before but I'm unable to reproduce.

The error is saying that it can't find `file:///opt/host-conda-bld/linux-64/`, but one of the first things done in the build script is `mkdir -p /opt/host-conda-bld/linux-64`.

Maybe if you don't have a local conda-build folder then that missing dir is still mounted to the docker container, but doing a mkdir has no effect in it. Can you try running `conda build` on a recipe (doesn't matter which one) to generate a local conda-build dir and see if that fixes things?

**Comment by sebastian-luna-valero** [comment]
Thanks @daler, that worked!

Is there something that you can do on `simulate-travis.py` to avoid this previous, manual step of using `conda build`?

**Comment by daler** [comment]
Possibly. Maybe creating a dummy recipe and building that. It's a one-time thing so it might be easier to add those instructions to the setup docs.

**Comment by sebastian-luna-valero** [comment]
Docs have been updated as a first attempt to prevent this issue:
https://github.com/bioconda/bioconda-utils/pull/62
