### ISSUE TITLE
bioconda-utils argument parsing problem

### ISSUE THREAD

**Issue by nfahlgren** [bioconda/bioconda-utils#553]
I am working on updating a recipe using the `bioconda-utils update` method. When I do a temporary install of bioconda-utils following the steps below I get an error, even if I just use the `-h` flag for help:

```bash
git clone git@github.com:bioconda/bioconda-recipes.git
cd bioconda-recipes
./bootstrap.py /tmp/miniconda
source ~/.config/bioconda/activate
bioconda-utils -h
```

This returns:

```
Traceback (most recent call last):
  File "/tmp/miniconda/miniconda/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 905, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/dispatching.py", line 327, in dispatch_commands
    add_commands(parser, functions)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/assembling.py", line 458, in add_commands
    set_default_command(command_parser, func)
  File "/tmp/miniconda/miniconda/lib/python3.6/site-packages/argh/assembling.py", line 287, in set_default_command
    sig=', '.join('/'.join(x) for x in xs)))
argh.exceptions.AssemblingError: do_lint: argument --only does not fit function signature: recipe_folder, config, --packages, --cache, --list-checks, -e/--exclude, --push-status, -u/--user, --commit, --push-comment, --pull-request, --repo, -g/--git-range, -f/--full-report, --pdb, --loglevel, --logfile, --logfile-level, --log-command-max-lines
```

Platforms tested: macOS 10.14 and CentOS 7.5

**Comment by nfahlgren** [comment]
Thanks @npavlovikj, that works for me also. It installed the latest release (0.15.13) but the options available do not match what's in the [documentation](https://bioconda.github.io/updating.html). Specifically this does not seem to be supported?

```
bioconda-utils update recipes/ config.yml --packages <my-package-name>
```

**Comment by npavlovikj** [comment]
Hopefully this helps https://github.com/bioconda/bioconda-utils/issues/409. The documentation needs updating on that part, but you should use `bioconda-utils autobump` instead.

**Comment by nfahlgren** [comment]
Ah okay, thanks @npavlovikj! 

Running `circleci build` with the latest `bioconda-utils-build-env` docker container seems to have the same issue with `bioconda-utils` above.

```bash
docker pull bioconda/bioconda-utils-build-env:latest
circleci build
```

Output:
```
Docker image digest: sha256:7b3f88035e74739f72373aff135919f3a42cf59006b2832ec6293afdf727c5c1
====>> Spin up Environment
Build-agent version 0.1.1250-22bf9f5d (2018-12-12T11:32:15+0000)
Starting container bioconda/bioconda-utils-build-env
  using image bioconda/bioconda-utils-build-env@sha256:871728819cfdd98e891dd8c83b4794f8c6331e60305c52468a474fce0f3ac43d

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1558542943
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=update-plantcv-3.3.0
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=https://github.com/bioconda/bioconda-recipes.git
  CIRCLE_SHA1=1064182797c2b003099f8a98edfc31b25cbebf4a
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1558542943
  CIRCLE_WORKING_DIRECTORY=~/project

====>> Checkout code
  #!/bin/bash -eo pipefail
mkdir -p /root/project && cp -r /tmp/_circleci_local_build_repo/. /root/project
====>> Setup ssh
  #!/bin/bash -eo pipefail
mkdir -p ~/.ssh
ssh-keyscan -H github.com >> ~/.ssh/known_hosts

# github.com SSH-2.0-babeld-80573d3e
====>> echo ". /opt/conda/etc/profile.d/conda.sh" >> $BASH_ENV
  #!/bin/bash -eo pipefail
echo ". /opt/conda/etc/profile.d/conda.sh" >> $BASH_ENV
====>> echo "conda activate" >> $BASH_ENV
  #!/bin/bash -eo pipefail
echo "conda activate" >> $BASH_ENV
====>> Download common definitions
  #!/bin/bash -eo pipefail
curl -s https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh > .circleci/common.sh

====>> Setup bioconda-utils
  #!/bin/bash -eo pipefail
.circleci/setup.sh
From https://github.com/bioconda/bioconda-recipes
 * [new branch]          master     -> __upstream__OU81coWjC0/master
bioconda-utils is /opt/conda/bin/bioconda-utils
====>> Linting
  #!/bin/bash -eo pipefail
bioconda-utils lint recipes config.yml \
--loglevel debug --full-report \
--git-range master HEAD

Traceback (most recent call last):
  File "/opt/conda/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/bioconda_utils/cli.py", line 905, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/opt/conda/lib/python3.6/site-packages/argh/dispatching.py", line 327, in dispatch_commands
    add_commands(parser, functions)
  File "/opt/conda/lib/python3.6/site-packages/argh/assembling.py", line 458, in add_commands
    set_default_command(command_parser, func)
  File "/opt/conda/lib/python3.6/site-packages/argh/assembling.py", line 287, in set_default_command
    sig=', '.join('/'.join(x) for x in xs)))
argh.exceptions.AssemblingError: do_lint: argument --only does not fit function signature: recipe_folder, config, --packages, --cache, --list-checks, -e/--exclude, --push-status, -u/--user, --commit, --push-comment, --pull-request, --repo, -g/--git-range, -f/--full-report, --pdb, --loglevel, --logfile, --logfile-level, --log-command-max-lines
Error: Exited with code 1
Step failed
Error: runner failed
{"Runner":true,"level":"error","msg":"runner failed","task-id":"localbuild-1558542943","time":"2019-05-22T16:36:53Z"}
Task failed
Error: job failed
```

**Comment by npavlovikj** [comment]
I have never been able to have `circleci build` running, and I have heard of other people having similar issues as well. I always use `bioconda-utils` - it also does the more stringent `mulled-test` that are performed on the build system anyways, so I would suggest you to use the same, https://bioconda.github.io/contribute-a-recipe.html#bootstrap-method.

**Comment by dpryan79** [comment]
I'll reiterate @npavlovikj's sage advise, stick with running `bioconda-utils` directly. If you're still getting the weird error with `bioconda-utils -h` then please post the output of `conda list`

**Comment by epruesse** [comment]
The `do_lint` error is my bad.

**Comment by nfahlgren** [comment]
That all fixed the issue, thanks @npavlovikj, @dpryan79 and @epruesse!
