### ISSUE TITLE
Packages won't build after incrementing build number

### ISSUE THREAD

**Issue by Hogfeldt** [bioconda/bioconda-utils#614]
While looking for test inputs for a tool we are building, we tried to test if the set of packages which, we where looking at, was able to be build with the recipe in bioconda-recipes. We did this test by just incrementing the build number of the package and then run the following command
```
bioconda-utils build recipes/ config.yml --packages <pgk-name>
```
The following packages failed to build:
- ac-diamond
- dawg
- dcmtk
- heinz
- livekraken
- meraculous
- openms
- regtools
- sailfish
- tn93
- verifybamid

Should thees packages be added to the blacklist file?

Here is some examples on the errors which came up
### ac-diamond
g++ throws compile errors, here is an example
```
08:48:08 BIOCONDA INFO (ERR) In file included from run/../output/output_format.h:26:0,
08:48:08 BIOCONDA INFO (ERR)                  from run/../output/output_buffer.h:25,
08:48:08 BIOCONDA INFO (ERR)                  from run/../output/output_file.h:25,
08:48:08 BIOCONDA INFO (ERR)                  from run/../output/join_blocks.h:26,
08:48:08 BIOCONDA INFO (ERR)                  from run/master_thread.h:27,
08:48:08 BIOCONDA INFO (ERR)                  from main.cpp:26:
08:48:08 BIOCONDA INFO (ERR) run/../output/../basic/score_matrix.h:167:22: error: ‘constexpr’ needed for in-class initialization of static data member ‘const double score_matrix::LN_2’ of non-integral type [-fpermissive]
```
### dawg:
g++ throws compile errors, here is an example:
```
08:56:20 BIOCONDA INFO (ERR) /home/per/.conda/envs/bioconda-ci/conda-bld/dawg_1569567287971/work/src/dawg.cpp:140:77: error: cannot convert ‘boost::logic::tribool’ to ‘bool’ in initialization
08:56:20 BIOCONDA INFO (ERR)   bool split  = arg.split || (indeterminate(arg.split) && glopts.output_split);
```
### dcmtk:
Compile errors example, here is an example:
```
09:01:31 BIOCONDA INFO (ERR) /home/per/.conda/envs/bioconda-ci/conda-bld/dcmtk_1569567599003/work/dcmsign/libsrc/sicertvf.cc:110:18: error: aggregate 'X509_STORE_CTX ctx' has incomplete type and cannot be defined
09:01:31 BIOCONDA INFO (ERR)    X509_STORE_CTX ctx;
```
### heinz:
Cmake errors:
```
09:05:21 BIOCONDA INFO (ERR) cmake: /home/per/.conda/envs/bioconda-ci/conda-bld/heinz_1569567894628/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by cmake)
09:05:21 BIOCONDA INFO (ERR) cmake: /home/per/.conda/envs/bioconda-ci/conda-bld/heinz_1569567894628/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by cmake)
09:05:21 BIOCONDA INFO (ERR) cmake: /home/per/.conda/envs/bioconda-ci/conda-bld/heinz_1569567894628/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by cmake)
09:05:21 BIOCONDA INFO (ERR) cmake: /home/per/.conda/envs/bioconda-ci/conda-bld/heinz_1569567894628/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by cmake)
```
### livekraken:
Errors while resolving conda environment
```
09:11:55 BIOCONDA INFO (OUT)   Build:
09:11:55 BIOCONDA INFO (OUT) source activate  /home/per/.conda/envs/bioconda-ci/conda-bld/_build_env
09:11:55 BIOCONDA INFO (OUT) 
09:11:55 BIOCONDA INFO (OUT) 
09:11:55 BIOCONDA INFO (ERR) Traceback (most recent call last):
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda_build/environ.py", line 756, in get_install_actions
09:11:55 BIOCONDA INFO (ERR)     actions = install_actions(prefix, index, specs, force=True)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
09:11:55 BIOCONDA INFO (ERR)     return f(*args, **kwds)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/plan.py", line 473, in install_actions
09:11:55 BIOCONDA INFO (ERR)     txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
09:11:55 BIOCONDA INFO (ERR)     force_remove, force_reinstall)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/core/solve.py", line 145, in solve_for_diff
09:11:55 BIOCONDA INFO (ERR)     force_remove)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/core/solve.py", line 242, in solve_final_state
09:11:55 BIOCONDA INFO (ERR)     ssc = self._run_sat(ssc)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
09:11:55 BIOCONDA INFO (ERR)     return f(*args, **kwds)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/core/solve.py", line 510, in _run_sat
09:11:55 BIOCONDA INFO (ERR)     ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs))
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
09:11:55 BIOCONDA INFO (ERR)     return f(*args, **kwds)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/resolve.py", line 1054, in solve
09:11:55 BIOCONDA INFO (ERR)     self.find_conflicts(specs)
09:11:55 BIOCONDA INFO (ERR)   File "/home/per/.conda/envs/bioconda-ci/lib/python3.6/site-packages/conda/resolve.py", line 316, in find_conflicts
09:11:55 BIOCONDA INFO (ERR)     raise UnsatisfiableError(bad_deps)
09:11:55 BIOCONDA INFO (ERR) conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
09:11:55 BIOCONDA INFO (ERR)   - argparse -> python=2.6 -> readline=6.2
09:11:55 BIOCONDA INFO (ERR)   - argparse -> python=2.6 -> sqlite=3.13
09:11:55 BIOCONDA INFO (ERR)   - argparse -> python=2.6 -> tk=8.5
09:11:55 BIOCONDA INFO (ERR)   - python[version='>=3.7,<3.8.0a0']
09:11:55 BIOCONDA INFO (ERR) Use "conda search <package> --info" to see the dependencies for each package.
```
### meraculous:
Cmake error
```
09:17:42 BIOCONDA INFO (ERR) CMake Error at CMakeLists.txt:34 (message):
09:17:42 BIOCONDA INFO (ERR)   Unsupported gcc version.  CMake will exit.
```
### openms:
CMake could not find all third party dependencies
```
09:25:20 BIOCONDA INFO (ERR) CMake Error at /home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
09:25:20 BIOCONDA INFO (ERR)   Failed to find "GL/gl.h" in
09:25:20 BIOCONDA INFO (ERR)   "/home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include;/home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/x86_64-conda_cos6-linux-gnu/sysroot/usr/include;/home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/libdrm;/home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/x86_64-conda_cos6-linux-gnu/sysroot/usr/include".
09:25:20 BIOCONDA INFO (ERR) Call Stack (most recent call first):
09:25:20 BIOCONDA INFO (ERR)   /home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:174 (include)
09:25:20 BIOCONDA INFO (ERR)   /home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:89 (find_package)
09:25:20 BIOCONDA INFO (ERR)   /home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt5OpenGL/Qt5OpenGLConfig.cmake:89 (find_package)
09:25:20 BIOCONDA INFO (ERR)   /home/per/.conda/envs/bioconda-ci/conda-bld/openms_1569568874095/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/cmake/Qt5/Qt5Config.cmake:28 (find_package)
09:25:20 BIOCONDA INFO (ERR)   doc/code_examples/CMakeLists.txt:53 (find_package)
09:25:20 BIOCONDA INFO (ERR) 
09:25:20 BIOCONDA INFO (ERR) 
09:25:22 BIOCONDA INFO (OUT) --   - Fido not found
09:25:22 BIOCONDA INFO (OUT) --   - FidoChooseParameters not found
09:25:22 BIOCONDA INFO (OUT) --   - Sirius not found
09:25:22 BIOCONDA INFO (OUT) --   - Novor not found
09:25:22 BIOCONDA INFO (OUT) --   - Crux not found
09:25:22 BIOCONDA INFO (OUT) --   - SpectraST not found
09:25:22 BIOCONDA INFO (OUT) -- Documentation is built (-D ENABLE_DOCS=On).
09:25:22 BIOCONDA INFO (OUT) -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
09:25:22 BIOCONDA INFO (OUT) -- Doxygen not found. Disabling all documentation targets!
09:25:22 BIOCONDA INFO (OUT) -- Note that no documentation will be installed alongside OpenMS.
09:25:22 BIOCONDA INFO (OUT) -- Configuring incomplete, errors occurred!
``` 
### regtools:
Probably a g++ compile error, a lot of warnings was thrown 
### sailfish:
Cmake error
```
09:38:08 BIOCONDA INFO (ERR) CMake Error at CMakeLists.txt:216 (message):
09:38:08 BIOCONDA INFO (ERR)   Sailfish cannot be compiled without Boost.
```
### tn93
g++ compile errors, here is an example
```
09:43:01 BIOCONDA INFO (ERR) /home/per/.conda/envs/bioconda-ci/conda-bld/tn93_1569570147957/work/src/tn93_shared.cc:325:10: error: reference to 'empty' is ambiguous
09:43:01 BIOCONDA INFO (ERR)    return empty;
09:43:01 BIOCONDA INFO (ERR)           ^~~~~
```
### verifybamid
Compile error
```
09:48:38 BIOCONDA INFO (ERR) Parameters.cpp:573:25: error: use of an operand of type ‘bool’ in ‘operator++’ is deprecated [-Werror=deprecated]
09:48:38 BIOCONDA INFO (ERR)              legacy_count++;
09:48:38 BIOCONDA INFO (ERR)                          ^~
09:48:39 BIOCONDA INFO (ERR) cc1plus: all warnings being treated as errors
```

**Comment by dpryan79** [comment]
Those will end up getting either fixed or blacklisted the next time someone needs to update or rebuild them, there's no need to preemptively do that though.

**Comment by Hogfeldt** [comment]
Okay. What are the criterias for a package to be added to the blacklist? Is when the recipe is to be updated, but it's not possible to create a recipe which can build the updated version?

**Comment by dpryan79** [comment]
The criteria are (A) the package is deprecated and should no longer be built or (B) there's a large-scale upgrade/build/release going on including a package and said package is preventing that process. For the most part packages end up on the blacklist when we change our pinnings and start rebuilding hundreds/thousands of packages.

**Comment by Hogfeldt** [comment]
Okay, thanks.
