### ISSUE TITLE
Bootstrap method fails because Python 3.7 is not found

### ISSUE THREAD

**Issue by npavlovikj** [bioconda/bioconda-utils#642]
Hi,

I usually use the `bootstrap` method to test recipes locally. However,  when I tried to re-install my environment with "**./bootstrap.py /tmp/miniconda**" on Linux yesterday, I got the following error:
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::aiofiles-0.4.0-py_1001'.
FileNotFoundError(2, "No such file or directory: '/tmp/miniconda/miniconda/bin/python3.7'")
Attempting to roll back.
Rolling back transaction: done
FileNotFoundError(2, "No such file or directory: '/tmp/miniconda/miniconda/bin/python3.7'")
Traceback (most recent call last):
  File "./bootstrap.py", line 118, in <module>
    sp.check_call(['.circleci/setup.sh'], env=env)
  File "/anaconda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.circleci/setup.sh']' returned non-zero exit status 1.
```

`bioconda_utils-requirements.txt` specifies `python >=3.7`, but somehow Python 3.6 is installed (`/tmp/miniconda/miniconda/bin/python3.6`).
I removed all old docker images in my system, `/tmp/miniconda` is new and empty directory, and I have the newest changes from the master branch.
The following conda-related versions are being installed:
```
    - conda-build==3.18.12
    - conda-forge-pinning==2019.09.27
    - conda-verify=3.1
    - conda==4.6.14
```
and Python 3.6 has been updated to Python 3.7 in the install step (python:                        3.6.5-hc3d631a_2                         --> 3.7.1-hd21baee_1001        conda-forge).

I know there have been recent changes in conda-forge Python packages, so I am not sure if this is related, or I am missing something in my setup.

Any suggestions and directions are highly appreciated! If you need any additional information, please let me know.

Thank you,
Natasha

**Comment by npavlovikj** [comment]
I am sorry for the bother, but can someone please help me with this? I keep encountering the same issue.

**Comment by thermokarst** [comment]
Hi @npavlovikj, I am not a bioconda team member, and I have no clue if this is an appropriate solution, but for me, I took a peek at [this bit of the `bootstrap.py` script](
https://github.com/bioconda/bioconda-recipes/blob/afe2268f8112a380cbffda03eabf7743ac64e455/bootstrap.py#L53-L55):

```python
# TODO: this mimics the override in the "common" job in .circleci/config.yaml
with open('.circleci/common.sh', 'w') as fout:
    fout.write("MINICONDA_VER=4.5.4\nBIOCONDA_UTILS_TAG=master\n")
```

The comment in there, 'this mimics the override in the "common" job in .circleci/config.yaml', led me to [this bit of circleci config](url):

So, opening up https://raw.githubusercontent.com/bioconda/bioconda-common/master/common.sh, I saw this:

```
MINICONDA_VER=4.6.14
BIOCONDA_UTILS_TAG=v0.16.11
```

This is a bit different than what is being written out in `bootstrap.py`: 

```python
"MINICONDA_VER=4.5.4\nBIOCONDA_UTILS_TAG=master\n"
```

I updated that line in my local `bootstrap.py` to read (matching the `common.sh` file, above)

```python
"MINICONDA_VER=4.6.14\nBIOCONDA_UTILS_TAG=v0.16.11\n"
```

From there, the bootstrap process proceeded as usual. Like I mentioned above though, I really have no clue if this is an appropriate fix or not, but it did work for me, YMMV.

Good luck!

**Comment by npavlovikj** [comment]
Hi @thermokarst ,

Thank you so much for your detailed response!

Indeed, after I changed `MINICONDA_VER=4.5.4` to `MINICONDA_VER=4.6.14` in "bootstrap.py", `./bootstrap.py /tmp/miniconda`  worked fine.
With the original script, `conda` does get updated to 4.6.14 though, that is why I didn't think it was a `conda` version issue.

I will leave this issue open in case someone from the core team would like to take a look at it - otherwise modifying "bootstrap.py" to use `MINICONDA_VER=4.6.14` locally worked for me.

Take care!

Thank you,
Natasha

**Comment by evolarjun** [comment]
Thanks @thermokarst for your investigation. Your fix worked for me too.

**Comment by blinard-BIOINFO** [comment]
Hi, still an issue on june 2020 with a fresh fork of bioconda.

Basically, until this fix is applied, the bootstrap script  appears to be broken when the latest version of conda are used.
Still, it is this method that is recomended in the tutorials to test recipes locally before merge requests. For new contributors, this would be a no go.

In my case, this translated as environement unsatisfiability:
```
Solving environment: failed
UnsatisfiableError: The following specifications were found to be in conflict:
  - networkx==1.11
  - python[version='>=3.7']
Use "conda search <package> --info" to see the dependencies for each package.
```
After following fix described above, no issues. But I  just spent 2 hours trying to understand why i got such a conflict with the bootsctrap script. Until finally I found the current thread.

**Comment by npavlovikj** [comment]
@blinard-BIOINFO , if you have updated your bioconda repo, can you please try replacing that line in the boostrap script with:
```
with open('.circleci/common.sh', 'w') as fout:
    fout.write("MINICONDA_VER=py37_4.8.2\nBIOCONDA_UTILS_TAG=v0.16.17\n")
```
and try it again?

**Comment by blinard-BIOINFO** [comment]
@npavlovikj , this is what I did, following instrucitons above. The setup was going further (base conda packages were downloaded) but hundreds of conflicts were still generated.

After more investigation, I found that I had to change also my channel priority.
My channel_priority was `strict` and unsolvable conflicts were stopping the script.

So to make bootstrap.py work in my setup I had to :
1) apply the circleci config fix described above
2) `conda config --set channel_priority false`
