### ISSUE TITLE
ImportError: No module named 'conda_build'

### ISSUE THREAD

**Issue by NickSto** [bioconda/bioconda-utils#67]
Hi, so I'm trying to set up my environment, and I thought I did everything correctly.

I installed conda to `~/src/miniconda3`, added `~/src/miniconda3/bin` to the end of my `PATH`, and installed `conda-build` via
`$ conda install conda-build`

Then I installed `bioconda-utils` via
`$ pip install --user git+https://github.com/bioconda/bioconda-utils.git`

I checked that `conda_build` is installed via
```
$ source ~/src/miniconda3/bin/activate
(root) $ python3 -m conda_build
/home/me/src/miniconda3/bin/python3: No module named conda_build.__main__; 'conda_build' is a package and cannot be directly executed
```

But I still get this error when I try to run `bioconda-utils`:
```
(root) $ bioconda-utils -h
Traceback (most recent call last):
  File "/home/me/.local/bin/bioconda-utils", line 9, in <module>
    load_entry_point('bioconda-utils==0.9.0', 'console_scripts', 'bioconda-utils')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/me/.local/lib/python3.5/site-packages/bioconda_utils/cli.py", line 16, in <module>
    from . import utils
  File "/home/me/.local/lib/python3.5/site-packages/bioconda_utils/utils.py", line 22, in <module>
    from conda_build import api
ImportError: No module named 'conda_build'
```

FYI, here are details about my environment:
```
(root) $ conda list
# packages in environment at /home/me/src/miniconda3:
#
beautifulsoup4            4.5.3                    py36_0  
cffi                      1.9.1                    py36_0  
chardet                   2.3.0                    py36_0  
conda                     4.3.11                   py36_0  
conda-build               2.1.4                    py36_0  
conda-env                 2.6.0                         0  
conda-verify              2.0.0                    py36_0  
cryptography              1.7.1                    py36_0  
filelock                  2.0.7                    py36_0  
idna                      2.2                      py36_0  
jinja2                    2.9.4                    py36_0  
libffi                    3.2.1                         1  
markupsafe                0.23                     py36_2  
openssl                   1.0.2k                        0  
patchelf                  0.9                           0  
pip                       9.0.1                    py36_1  
pkginfo                   1.4.1                    py36_0  
pyasn1                    0.1.9                    py36_0  
pycosat                   0.6.1                    py36_1  
pycparser                 2.17                     py36_0  
pycrypto                  2.6.1                    py36_4  
pyopenssl                 16.2.0                   py36_0  
python                    3.6.0                         0  
pyyaml                    3.12                     py36_0  
readline                  6.2                           2  
requests                  2.12.4                   py36_0  
ruamel_yaml               0.11.14                  py36_1  
setuptools                27.2.0                   py36_0  
six                       1.10.0                   py36_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
wheel                     0.29.0                   py36_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zlib                      1.2.8                         3

(root) $ conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : 2.1.4
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/me/src/miniconda3  (writable)
    default environment : /home/me/src/miniconda3
       envs directories : /home/me/src/miniconda3/envs
                          /home/me/.conda/envs
          package cache : /home/me/src/miniconda3/pkgs
                          /home/me/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /home/me/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-62-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

(root) $ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
beautifulsoup4 (4.5.3)
cffi (1.9.1)
chardet (2.3.0)
conda (4.3.11)
conda-build (2.1.4)
conda-verify (2.0.0)
cryptography (1.7.1)
filelock (2.0.7)
idna (2.2)
Jinja2 (2.9.4)
MarkupSafe (0.23)
pip (9.0.1)
pkginfo (1.4.1)
pyasn1 (0.1.9)
pycosat (0.6.1)
pycparser (2.17)
pycrypto (2.6.1)
pyOpenSSL (16.2.0)
PyYAML (3.12)
requests (2.12.4)
setuptools (27.2.0)
six (1.10.0)
wheel (0.29.0)
```

**Comment by yesimon** [comment]
I would also suggest using an older version of `conda-build`. I recently tried `2.0.0` which seems to work for me

**Comment by NickSto** [comment]
Thanks for the suggestion. I'm not sure why, but when I try that, I get this error:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - conda-build 2.0.0* -> python 2.7*
  - python 3.6*
```
I'm using miniconda3, as required by bioconda.

**Comment by tomkinsc** [comment]
Are you able to pin conda-build to the py35 version?

`conda install conda-build=2.0.0=py35_0`

**Comment by yesimon** [comment]
I believe it's because `conda-build` doesn't have a package for python 3.6

**Comment by johanneskoester** [comment]
The conda build version you had initially should work fine. Are you sure that you use the Python interpreter from miniconda when running bioconda-utils?

**Comment by NickSto** [comment]
Ah, I think I see what might be happening. `bioconda-utils` has `/usr/bin/python3` hard-coded into the shebang line. When I enter the conda environment and invoke `python`, it runs the conda version. But when I execute `bioconda-utils`, it's still invoking the hard-coded `/usr/bin/python3`, which doesn't see the `conda_build` module:
```
$ /usr/bin/python3 -m conda_build
/usr/bin/python3: No module named conda_build
```
Shouldn't `bioconda-utils`'s shebang be `#!/usr/bin/env python3`?

**Comment by johanneskoester** [comment]
Yes, definitely! I'll fix it.

**Comment by epruesse** [comment]
Closing - probably out of date
