### ISSUE TITLE
Error when trying to run bioconda-utils

### ISSUE THREAD

**Issue by vinisalazar** [bioconda/bioconda-utils#694]
Hi, I installed `bioconda-utils` as instructed on [this page](https://bioconda.github.io/contributor/updating.html#updating-recipes-for-a-pinning-change).

When I run the following command:

`bioconda-utils autobump recipes/ config.yml --packages bioprov`

The command starts to run and the "Loading recipes" progress bar starts to fill. When it's done, it raises the following error:

```
13:38:14 BIOCONDA INFO Building Recipe DAG: done (6761 nodes, 20306 edges)
13:38:14 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 847, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/vini/anaconda3/envs/bioconda-utils/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 971, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-20>", line 5, in autobump
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 130, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-19>", line 5, in autobump
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 59, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-18>", line 5, in autobump
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 847, in autobump
    config_dict, cache_fn=cache and cache + "_dag.pkl")
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/autobump.py", line 133, in __init__
    self.dag = graph.filter_recipe_dag(self.dag, packages, exclude)
  File "/Users/vini/anaconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/graph.py", line 127, in filter_recipe_dag
    and not any(fnmatch(recipe.reldir, p) for p in exclude)):
TypeError: 'NoneType' object is not iterable
```

I tried reinstalling bioconda-utils a few times, but to no avail. Any ideas on how to proceed?

Thank you for any assistance you can provide,

V

**Comment by dpryan79** [comment]
Definitely seems like a bug. This is mostly run as a cron job without specifying `--packages` (the source of the bot's PRs), so I imagine there's some issue with how `--packages bioprov` is being handled.
