### ISSUE TITLE
complains about valid use of `insteadOf` in my .gitconfig

### ISSUE THREAD

**Issue by mr-c** [bioconda/bioconda-utils#723]
In sections that do not pertain to my use of bioconda-utils

```
$ bioconda-utils autobump recipes/ config.yml --packages cwltest --create-pr
[…]
14:11:41 BIOCONDA ERROR Dropping into debugger
Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/collections/__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/collections/__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'insteadOf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 875, in autobump
    git_handler = BiocondaRepo(recipe_folder, dry_run)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 503, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 134, in get_remote
    old = reader.get(section, 'insteadOf')
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/git/config.py", line 77, in assure_data_present
    return func(self, *args, **kwargs)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'insteadOf' in section: 'url "git+ssh://misterc@git.launchpad.net/"'
Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/configparser.py", line 788, in get
    value = d[option]
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/collections/__init__.py", line 914, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/collections/__init__.py", line 906, in __missing__
    raise KeyError(key)
KeyError: 'insteadOf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/bioconda-utils/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 971, in main
    bioconductor_skeleton, clean_cran_skeleton, autobump, bot
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 328, in dispatch_commands
    dispatch(parser, *args, **kwargs)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
    for line in lines:
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
    for line in result:
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/argh/dispatching.py", line 260, in _call
    result = function(*positional, **keywords)
  File "<boltons.funcutils.FunctionBuilder-20>", line 5, in autobump
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 130, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-19>", line 5, in autobump
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 59, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-18>", line 5, in autobump
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 71, in wrapper
    func(*args, **kwargs)
  File "<boltons.funcutils.FunctionBuilder-17>", line 5, in autobump
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 90, in wrapper
    func(*args, **kwargs)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/cli.py", line 875, in autobump
    git_handler = BiocondaRepo(recipe_folder, dry_run)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 503, in __init__
    super().__init__(repo, dry_run, home, fork, allow_dirty)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 83, in __init__
    self.home_remote = self.get_remote(home)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/bioconda_utils/githandler.py", line 134, in get_remote
    old = reader.get(section, 'insteadOf')
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/site-packages/git/config.py", line 77, in assure_data_present
    return func(self, *args, **kwargs)
  File "/home/michael/miniconda3/envs/bioconda-utils/lib/python3.7/configparser.py", line 791, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'insteadOf' in section: 'url "git+ssh://misterc@git.launchpad.net/"'
```

Relevant section of my `.gitconfig`
```
[url "git+ssh://misterc@git.launchpad.net/"]                                    
        insteadof = lp: 
```

**Comment by dpryan79** [comment]
@mbargull This is presumably a gitpython bug, do you happen to know if we need to keep our current pinning to >=3.0.8,3.0.* for any reason and not allow 3.1?
