### ISSUE TITLE
argh.exceptions.AssemblingError when using bioconda-utils

### ISSUE THREAD

**Issue by matrulda** [bioconda/bioconda-utils#929]
Hi! I'm having issues using the `bioconda-utils`: 

I installed mamba with https://github.com/conda-forge/miniforge#mambaforge and then ran: 

```
mamba create -n bioconda -c conda-forge -c bioconda bioconda-utils
mamba activate bioconda
```

However, it gives me this error for all commands (except `--version`, which returns the version):
```
$ bioconda-utils -h
Traceback (most recent call last):
  File "/home/matilda/miniforge3/envs/bioconda/bin/bioconda-utils", line 10, in <module>
    sys.exit(main())
  File "/home/matilda/miniforge3/envs/bioconda/lib/python3.8/site-packages/bioconda_utils/cli.py", line 1109, in main
    argh.dispatch_commands([
  File "/home/matilda/.local/lib/python3.8/site-packages/argh/dispatching.py", line 348, in dispatch_commands
    add_commands(parser, functions)
  File "/home/matilda/.local/lib/python3.8/site-packages/argh/assembling.py", line 457, in add_commands
    set_default_command(command_parser, func)
  File "/home/matilda/.local/lib/python3.8/site-packages/argh/assembling.py", line 263, in set_default_command
    raise AssemblingError(
argh.exceptions.AssemblingError: build: argument --loglevel does not fit function signature: recipe_folder, config, --packages, --git-range, --testonly, --force, --docker, --mulled-test, --build_script_template, --pkg_dir, --anaconda-upload, --mulled-upload-target, --build-image, --keep-image, --lint/--prelint, --lint-exclude, --check-channels, --n-workers, --worker-offset, --keep-old-work, --mulled-conda-image, --docker-base-image, --record-build-failures, --skiplist-leafs
```
Can you help me figure out what the issue is? Thanks! 

Versions
OS: Ubuntu 22.04.3 LTS
bioconda-utils: 2.4.0 (I noticed this is not the newest version, i tried to install https://github.com/bioconda/bioconda-utils/releases/tag/v2.7.0 by cloning the repo and installing manually, but get the same error.) 
mamba: 1.4.2
conda: 23.3.1

**Comment by aliciaaevans** [comment]
@matrulda bioconda-utils 2.8.0 has been released and pushed to the channel now. Can you give it a try with a fresh conda environment and see if you still have the issue?

**Comment by matrulda** [comment]
Sorry for the very late reply! @aliciaaevans I tried setting up a new environment with conda (23.10.0):
```
conda create -n bioconda -c conda-forge -c bioconda bioconda-utils
``` 
It installed bioconda-utils v2.11.1, but I still have the same issue. It has to be something with my setup, but I really don't understand what. I have tried to re-install mamba/conda, but the result is the same :shrug:
